"""drop_quarantined_columns

Revision ID: 2e40c092d03b
Revises: 
Create Date: 2026-05-15 10:26:55.041835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e40c092d03b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flotteur', 'numero_immatriculation')
    op.drop_column('operation', 'seconde_autorite')
    op.drop_column('operation', 'cross_sitrep')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('cross_sitrep', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('operation', sa.Column('seconde_autorite', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('flotteur', sa.Column('numero_immatriculation', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
